package ru.mrmilegit.rpgthings.lib;

import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.AdvancedModelLoader;
import net.minecraftforge.client.model.IModelCustom;

public class PTTReference {

   public static final String MOD_ID = "rpgthings";
   public static final String MOD_NAME = "Rpg Things";
   public static final String VERSION = "3.0";
   public static final String SERVER_PROXY_CLASS = "ru.mrmilegit.rpgthings.proxy.RpgThingsCommonProxy";
   public static final String CLIENT_PROXY_CLASS = "ru.mrmilegit.rpgthings.proxy.RpgThingsClientProxy";
   public static final IModelCustom MODEL_GHOST_IRON_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ghostIronSmall.obj"));
   public static final IModelCustom MODEL_GHOST_IRON_SMALL_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ghostIronSmallCrystal.obj"));
   public static final IModelCustom MODEL_GHOST_IRON_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ghostIronBig.obj"));
   public static final IModelCustom MODEL_GHOST_IRON_BIG_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ghostIronBigCrystal.obj"));
   public static final IModelCustom MODEL_GHOST_IRON_GEM = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/Crystal.obj"));
   public static final IModelCustom MODEL_OBSIDIAN = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/Obsidian.obj"));
   public static final IModelCustom MODEL_OBSIDIAN_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ObsidianCrystal.obj"));
   public static final IModelCustom MODEL_STARMETAL_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/StarmetalSmall.obj"));
   public static final IModelCustom MODEL_STARMETAL_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/StarmetalBig.obj"));
   public static final IModelCustom MODEL_N2OBSIDIAN_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/N2ObsidianSmall.obj"));
   public static final IModelCustom MODEL_N2OBSIDIAN_SMALL_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/N2ObsidianSmallCrystal.obj"));
   public static final IModelCustom MODEL_N2OBSIDIAN_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/N2ObsidianBig.obj"));
   public static final IModelCustom MODEL_N2OBSIDIAN_BIG_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/N2ObsidianBigCrystal.obj"));
   public static final IModelCustom MODEL_ADAMANTIUM = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/AdamantiumOre.obj"));
   public static final IModelCustom MODEL_ADAMANTIUM_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/AdamantiumCrystal.obj"));
   public static final IModelCustom MODEL_ANCIENTGEM = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/AncientgemOre.obj"));
   public static final IModelCustom MODEL_ANCIENTGEM_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/AncientgemCrystal.obj"));
   public static final IModelCustom MODEL_BLACKROCK_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/BlackrockSmall.obj"));
   public static final IModelCustom MODEL_BLACKROCK_SMALL_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/BlackrockSmallCrystal.obj"));
   public static final IModelCustom MODEL_BLACKROCK_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/BlackrockBig.obj"));
   public static final IModelCustom MODEL_BLACKROCK_BIG_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/BlackrockBigCrystal.obj"));
   public static final IModelCustom MODEL_FELSLATE_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/FelslateSmall.obj"));
   public static final IModelCustom MODEL_FELSLATE_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/FelslateBig.obj"));
   public static final IModelCustom MODEL_LEYSTONE_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/LeystoneSmall.obj"));
   public static final IModelCustom MODEL_LEYSTONE_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/LeystoneBig.obj"));
   public static final IModelCustom MODEL_COBALT = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/CobaltOre.obj"));
   public static final IModelCustom MODEL_COBALT_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/CobaltCrystal.obj"));
   public static final IModelCustom MODEL_ELEMENTIUM_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ElementiumSmall.obj"));
   public static final IModelCustom MODEL_ELEMENTIUM_SMALL_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ElementiumSmallCrystal.obj"));
   public static final IModelCustom MODEL_ELEMENTIUM_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ElementiumBig.obj"));
   public static final IModelCustom MODEL_ELEMENTIUM_BIG_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ElementiumBigCrystal.obj"));
   public static final IModelCustom MODEL_TRUEIRON_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/TrueironSmall.obj"));
   public static final IModelCustom MODEL_TRUEIRON_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/TrueironBig.obj"));
   public static final IModelCustom MODEL_TRILLIUM_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/TrilliumSmall.obj"));
   public static final IModelCustom MODEL_TRILLIUM_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/TrilliumBig.obj"));
   public static final IModelCustom MODEL_THORIUM_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ThoriumSmall.obj"));
   public static final IModelCustom MODEL_THORIUM_SMALL_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ThoriumSmallCrystal.obj"));
   public static final IModelCustom MODEL_THORIUM_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ThoriumBig.obj"));
   public static final IModelCustom MODEL_THORIUM_BIG_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/ThoriumBigCrystal.obj"));
   public static final IModelCustom MODEL_PYRIUM_SMALL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/PyriumSmall.obj"));
   public static final IModelCustom MODEL_PYRIUM_SMALL_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/PyriumSmallCrystal.obj"));
   public static final IModelCustom MODEL_PYRIUM_BIG = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/PyriumBig.obj"));
   public static final IModelCustom MODEL_PYRIUM_BIG_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/PyriumBigCrystal.obj"));
   public static final IModelCustom MODEL_PYRIUM_BIG_CRYSTAL_SECOND = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/PyriumBigCrystalSecond.obj"));
   public static final IModelCustom MODEL_FELIRON = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/FelironOre.obj"));
   public static final IModelCustom MODEL_FELIRON_CRYSTAL = AdvancedModelLoader.loadModel(new ResourceLocation("rpgthings:models/FelironCrystal.obj"));
   public static final ResourceLocation TEXTURE_EMERALD_SMALL = new ResourceLocation("rpgthings", "models/EmeraldSmall.png");
   public static final ResourceLocation TEXTURE_EMERALD_BIG = new ResourceLocation("rpgthings", "models/EmeraldBig.png");
   public static final ResourceLocation TEXTURE_EMERALD_CRYSTAL = new ResourceLocation("rpgthings", "models/EmeraldGem.png");
   public static final ResourceLocation TEXTURE_OBSIDIAN = new ResourceLocation("rpgthings", "models/ObsidianOre.png");
   public static final ResourceLocation TEXTURE_OBSIDIAN_CRYSTAL = new ResourceLocation("rpgthings", "models/ObsidianOre.png");
   public static final ResourceLocation TEXTURE_STARMETAL = new ResourceLocation("rpgthings", "models/Starmetal.png");
   public static final ResourceLocation TEXTURE_N2OBSIDIAN_SMALL = new ResourceLocation("rpgthings", "models/N2ObsidianSmall.png");
   public static final ResourceLocation TEXTURE_N2OBSIDIAN_BIG = new ResourceLocation("rpgthings", "models/N2ObsidianBig.png");
   public static final ResourceLocation TEXTURE_N2OBSIDIAN_CRYSTAL = new ResourceLocation("rpgthings", "models/N2ObsidianCrystal.png");
   public static final ResourceLocation TEXTURE_ADAMANTIUM = new ResourceLocation("rpgthings", "models/AdamantiumOre.png");
   public static final ResourceLocation TEXTURE_ADAMANTIUM_CRYSTAL = new ResourceLocation("rpgthings", "models/AdamantiumCrystal.png");
   public static final ResourceLocation TEXTURE_ANCIENTGEM = new ResourceLocation("rpgthings", "models/AncientgemOre.png");
   public static final ResourceLocation TEXTURE_ANCIENTGEMBIG = new ResourceLocation("rpgthings", "models/AncientgemOreBig.png");
   public static final ResourceLocation TEXTURE_ANCIENTGEM_CRYSTAL = new ResourceLocation("rpgthings", "models/AncientgemCrystal.png");
   public static final ResourceLocation TEXTURE_BLACKROCK = new ResourceLocation("rpgthings", "models/BlackrockOre.png");
   public static final ResourceLocation TEXTURE_BLACKROCK_CRYSTAL = new ResourceLocation("rpgthings", "models/BlackrockCrystal.png");
   public static final ResourceLocation TEXTURE_FELSLATE = new ResourceLocation("rpgthings", "models/FelslateOre.png");
   public static final ResourceLocation TEXTURE_LEYSTONE = new ResourceLocation("rpgthings", "models/LeystoneOre.png");
   public static final ResourceLocation TEXTURE_COBALT = new ResourceLocation("rpgthings", "models/CobaltOre.png");
   public static final ResourceLocation TEXTURE_COBALTBIG = new ResourceLocation("rpgthings", "models/CobaltOreBig.png");
   public static final ResourceLocation TEXTURE_COBALT_CRYSTAL = new ResourceLocation("rpgthings", "models/CobaltCrystal.png");
   public static final ResourceLocation TEXTURE_ELEMENTIUM = new ResourceLocation("rpgthings", "models/ElementiumOre.png");
   public static final ResourceLocation TEXTURE_ELEMENTIUM_CRYSTAL = new ResourceLocation("rpgthings", "models/ElementiumCrystal.png");
   public static final ResourceLocation TEXTURE_TRUEIRON = new ResourceLocation("rpgthings", "models/TrueironOre.png");
   public static final ResourceLocation TEXTURE_TRILLIUM = new ResourceLocation("rpgthings", "models/TrilliumOre.png");
   public static final ResourceLocation TEXTURE_THORIUM = new ResourceLocation("rpgthings", "models/ThoriumOre.png");
   public static final ResourceLocation TEXTURE_THORIUM_CRYSTAL = new ResourceLocation("rpgthings", "models/ThoriumCrystal.png");
   public static final ResourceLocation TEXTURE_PYRIUM = new ResourceLocation("rpgthings", "models/PyriumOre.png");
   public static final ResourceLocation TEXTURE_PYRIUM_CRYSTAL = new ResourceLocation("rpgthings", "models/PyriumCrystal.png");
   public static final ResourceLocation TEXTURE_PYRIUM_CRYSTAL_SECOND = new ResourceLocation("rpgthings", "models/PyriumCrystalSecond.png");
   public static final ResourceLocation TEXTURE_FELIRON = new ResourceLocation("rpgthings", "models/FelironOre.png");
   public static final ResourceLocation TEXTURE_FELIRON_BIG = new ResourceLocation("rpgthings", "models/FelironOreBig.png");
   public static final ResourceLocation TEXTURE_FELIRON_CRYSTAL = new ResourceLocation("rpgthings", "models/FelironCrystal.png");
   public static final ResourceLocation TEXTURE_KHORIUM = new ResourceLocation("rpgthings", "models/KhoriumOre.png");
   public static final ResourceLocation TEXTURE_KHORIUM_BIG = new ResourceLocation("rpgthings", "models/KhoriumOreBig.png");
   public static final ResourceLocation TEXTURE_KHORIUM_CRYSTAL = new ResourceLocation("rpgthings", "models/KhoriumCrystal.png");
}
